config/routes.rb
Rails.application.routes.draw do
  resources :workouts
  resources :exercises
  resources :clients
  resources :instructors
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/client.rb
class Client < ApplicationRecord
  belongs_to :instructor
  has_many client_workouts
  has_many :workouts, through: :client_workouts

end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: %i[ show edit update destroy ]

  # GET /clients or /clients.json
  def index
    @clients = Client.all
  end

  # GET /clients/1 or /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients or /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to client_url(@client), notice: "Client was successfully created." }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1 or /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to client_url(@client), notice: "Client was successfully updated." }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1 or /clients/1.json
  def destroy
    @client.destroy

    respond_to do |format|
      format.html { redirect_to clients_url, notice: "Client was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def client_params
      params.require(:client).permit(:firstname, :lastname, :email, :mobile, :sex, :weight, :height, :dob, :instructor_id)
    end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/_form.html.erb
<%= form_with(model: client) do |form| %>
  <% if client.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
        <% client.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :firstname %>
    <%= form.text_field :firstname %>
  </div>

  <div class="field">
    <%= form.label :lastname %>
    <%= form.text_field :lastname %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :mobile %>
    <%= form.number_field :mobile %>
  </div>

  <div class="field">
    <%= form.label :sex %>
    <%= form.text_field :sex %>
  </div>

  <div class="field">
    <%= form.label :weight %>
    <%= form.number_field :weight %>
  </div>

  <div class="field">
    <%= form.label :height %>
    <%= form.number_field :height %>
  </div>

  <div class="field">
    <%= form.label :dob %>
    <%= form.date_select :dob %>
  </div>

  <div class="field">
    <%= form.label :instructor_id %>
    <%= form.text_field :instructor_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/clients/edit.html.erb
<h1>Editing Client</h1>

<%= render 'form', client: @client %>

<%= link_to 'Show', @client %> |
<%= link_to 'Back', clients_path %>

app/views/clients/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Clients</h1>

<table>
  <thead>
    <tr>
      <th>Firstname</th>
      <th>Lastname</th>
      <th>Email</th>
      <th>Mobile</th>
      <th>Sex</th>
      <th>Weight</th>
      <th>Height</th>
      <th>Dob</th>
      <th>Instructor</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @clients.each do |client| %>
      <tr>
        <td><%= client.firstname %></td>
        <td><%= client.lastname %></td>
        <td><%= client.email %></td>
        <td><%= client.mobile %></td>
        <td><%= client.sex %></td>
        <td><%= client.weight %></td>
        <td><%= client.height %></td>
        <td><%= client.dob %></td>
        <td><%= client.instructor_id %></td>
        <td><%= link_to 'Show', client %></td>
        <td><%= link_to 'Edit', edit_client_path(client) %></td>
        <td><%= link_to 'Destroy', client, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Client', new_client_path %>

app/views/clients/new.html.erb
<h1>New Client</h1>

<%= render 'form', client: @client %>

<%= link_to 'Back', clients_path %>

app/views/clients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Firstname:</strong>
  <%= @client.firstname %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @client.lastname %>
</p>

<p>
  <strong>Email:</strong>
  <%= @client.email %>
</p>

<p>
  <strong>Mobile:</strong>
  <%= @client.mobile %>
</p>

<p>
  <strong>Sex:</strong>
  <%= @client.sex %>
</p>

<p>
  <strong>Weight:</strong>
  <%= @client.weight %>
</p>

<p>
  <strong>Height:</strong>
  <%= @client.height %>
</p>

<p>
  <strong>Dob:</strong>
  <%= @client.dob %>
</p>

<p>
  <strong>Instructor:</strong>
  <%= @client.instructor_id %>
</p>

<br>
<table>
  <caption style="text-align:centre"><h3>Workouts</h3></caption>
  <thead>
    <tr>
      <th>Type</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @client.workouts.each do |workout| %>
      <tr>
        <td><%= workout.firstname %></td>
        <td><%= workout.lastname %></td>
        <td><%= link_to 'Show', workout %></td>
        <td><%= link_to 'Edit', edit_workout_path(workout) %></td>
        <td><%= link_to 'Destroy', workout, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

<%= link_to 'Edit', edit_client_path(@client) %> |
<%= link_to 'Back', clients_path %>